### ISSUE TITLE
Screen shots?

### ISSUE THREAD

**Issue by PySimpleGUI** [Kevinpgalligan/BeatlesAndYou#1]
It would be great to see the GUI / output that your project creates.  Nothing gets other people's attention like a picture.   The project description sounds really interesting and got my attention.  Adding an image is likely to get the attention of others as well.

An easy way to add a screenshot to your project's homepage:
* Upload an image to a GitHub issue (like this issue) by dragging and dropping or pasting into the issue
* Copy/paste the link that is shown in the GitHub issue into your readme.md file

**Comment by Kevinpgalligan** [comment]
Hey, thanks for chipping in! And thanks for providing such an easy-to-use library. This is a work in progress, hence the sparse description. I'll flesh out the readme a bit more once the project is finished 🙂
